#https://github.com/localstack/localstack
#https://github.com/localstack/localstack/blob/master/docker-compose.yml
#https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints#localstack
version: '2.1'
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
    - SERVICES=acm,apigateway,cloudformation,cloudwatch,dynamodb,dynamodbstreams,es,firehose,iam,kinesis,lambda,route53,redshift,s3,secretsmanager,ses,sns,sqs,ssm,stepfunctions,sts
    - DEBUG=1
    - DATA_DIR=/data
    - PORT_WEB_UI=${PORT_WEB_UI- }
    - LAMBDA_EXECUTOR=docker
    - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
    - DOCKER_HOST=unix:///var/run/docker.sock
    - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
    - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    - "/var/run/docker.sock:/var/run/docker.sock"